baseURL = 'https://niuai.org/'
languageCode = 'en-us'
title = 'NIU AI & ML Community'
theme = 'PaperMod'

[params]
  description = "NIU AI and Machine Learning Study Community"
  author = "Lei Zhang"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowFullTextinRSS = true
  assets.favicon = "favicon.ico"
  ShowCover = true
  
  [params.cover]
    linkFullImages = true
    responsiveImages = true
    hiddenInSingle = true
  
  [params.label]
    text = ""
    icon = "/images/niuai.org.png"
    iconHeight = 35
  
  # NIU Colors
  defaultTheme = "light"
  
  [params.homeInfoParams]
  Title = "Welcome to NIU AI"
  Content = """
  **Stay Connected:** [Subscribe](/subscribe) to receive notifications about upcoming seminars 
  and new presentations.

  **Share a Talk or Presentation:** Interested in giving a talk or presentation? 
  Contact us at contact@niuai.org
  """

[[menu.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menu.main]]
  name = 'Presentations'
  pageRef = '/presentations'
  weight = 20

[[menu.main]]
  name = 'Projects'
  pageRef = '/projects'
  weight = 30

[[menu.main]]
  name = 'About'
  pageRef = '/about'
  weight = 40

[[menu.main]]
  name = 'Subscribe'
  pageRef = '/subscribe'
  weight = 50

[taxonomies]
  tag = 'tags'
  category = 'categories'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true